jupyterhub/chartpress

chartpress.py

avoids overwriting tag argument for subsequent images
fixes missing image tags in https://github.com/jupyterhub/binderhub/pull/468

fix image tag when building multiple images

---

chartpress.py

Fixes #3.
Adds a check for the `images` key in the `chart` dictionary and only runs the images functions if it exists.

Make images optional

---

chartpress.py

This change adds the option to overwrite the `imagePrefix` option from `chartpress.yaml`.
This allows to fork, modify and test a project without having to edit `chartpress.yaml`, as you can then publish container images to a different Docker registry and/or repository.

Added option to change docker image prefix

---

chartpress.py

workaround bizarre ruamel.yaml bug that results in unquoted strings that are all-digits and start with 0 and contain an 8 or 9.
closes #15

ensure tag string is quoted

---

chartpress.py

The yaml parser creates objects which do not have `dict` as a parent class, but `collections.abc.MutableMapping`.
See source for `ruamel.yaml.comments.CommentedMap`: https://bitbucket.org/ruamel/yaml/src/c177aa5d95fd92911eba4b40d60ac20b4e940105/comments.py?at=default&fileviewer=file-view-default#comments.py-595

Fix build_values mapping check

---

chartpress.py

chart versions should be version strings, but tags may have a leading ‘v’. Strip the v from the chart version if it’s there.

avoid adding ‘v’ to chart version when using `--tag vX.Y`

---

setup.py

Declare that we require Python 3.6

---

.travis.yml
CHANGELOG.md
chartpress.py
setup.py

checks presence of images locally and on registry for need to build/push.
This provides a much more reliable check than the commit range.
Commit range is now completely ignored.
additionally, for debugging and transparency, echo shell commands that are executed.
closes #23

check for image existence

---

README.md
chartpress.py

Provide a `--sanitize` option to reset the image tags. This is useful to avoid committing unwanted changes to chart image tags.

provide a reset option to reset image tags and chart version

---

chartpress.py

Some yaml values might be converted to e.g. boolean - for example, an unquoted "off" can get rendered as "false". This has made our nginx-ingress break in a way that was quite difficult to debug and can be avoided with the `preserve_quotes` flag in this PR.

avoid mangling of quotes in rendered charts (#1)

---

README.md

The README.md has output of `chartpress --help` within it, this output was outdated and made me miss out on recent developments such as `--image-prefix`, `--reset`, and `--skip-build`.

Update chartpress --help output in README.md

---

.travis.yml
CHANGELOG.md
README.md
chartpress.py

I don't know for sure how this failed silently, but it didn't actually do what it should before on the z2jh repo.
It contains two commits from #45 about the --version flag.

Refresh .travis.yml

---

.travis.yml
CHANGELOG.md
chartpress.py

This is a continuation of @minrk's PR #33 where I implement my suggestion in https://github.com/jupyterhub/chartpress/pull/33#issuecomment-542196738.
1. I made the Chart version set itself prefixed with the latest tag found in the branch commit history instead of using a very specific manipulation of the value in Chart.yaml.
1. I made the Chart version set itself suffixed with `+<n_commits_since_tag>.<last_chart_modifying_commit>`, which results in a valid formatted SemVer 2 version.
1. I made the image tags follow the same pattern as the Chart version, but relating to the latest image commit instead of the latest chart commit. There is a difference, and that is that `+` is replaced with `_` to comply with the allowed characters of docker tags.
1. I made the Chart.yaml's `--reset` …

Chart and image versioning, and Chart.yaml's --reset interaction

---

README.md
chartpress.py

If we reset this value to something else than a valid SemVer 2 version
string, then helm lint on the chart would fail. So, in this PR I make it default to `0.0.1-set.by.chartpress` which is a valid SemVer 2 version, and allow the user to customize this through `chartpress.yaml`'s resetVersion field.

Reset Chart.yaml's version to a valid value

---

.travis.yml
README.md
chartpress.py

This PR adds the `--long` flag to always output build information in image tags and chart version. This mimics `git describe --long` that has does something very similar.
The `--long` flag could be useful to avoid producing duplicate entries when a build job is run twice, once because of a commit was pushed, and once again because of a tag was pushed and coupled with this commit. If `--long` us used with pushed commits, but not for pushed tags or with `--tag`, then we wouldn't risk pushing two charts of the same version for example.

--long flag to always output build information in image tags and chart version

---

.travis.yml
README.md
chartpress.py
tests/test_regexp.py

Closes #62 that followed an issue introduced by #52 by implementing https://github.com/jupyterhub/chartpress/issues/62#issuecomment-544377062 and catching some past mistakes of mine along the way. Fixing #62 is urgent as chartpress 0.4.2 is breaking expected functionality of chartpress.
- **image tag:** Found and fixed a bug from #62 relating to the use of `-` instead of `.` as separator for image tags, which was not according to plan or inline documentation.
- **g prefix:** Stripped away a "g" prefix that follows from use of git describe.
- **Ignored tags:** Fixed lacking ability to handle tags after latest modification commit, and renamed function to reflect this.
- Deleted a remnant function of past logic: `last_modified_date(*paths)`.
- Added pytest tests for simple to test functions …

Fix bugs: index merge, image tag, g prefix, ignored tags

---

CHANGELOG.md
chartpress.py

Decision is based on the type of the field being set. If `valuesPath` points to a dict, set it the current `repository:, tag:` way, if it's a string, set a single `repository:tag` image string.
enables e.g. using chartpress to build images in `profileList` in zero-to-jupyterhub:
```yaml
charts:
- name: jupyterhub
images:
default:
valuesPath: jupyterhub.singleuser.profileList.0.kubespawner_override.image
gap:
valuesPath: jupyterhub.singleuser.profileList.1.kubespawner_override.image
```
closes #10
closes #39 (edit by @consideRatio)

support string images and items in lists

---

chartpress.py

git describe shows current commit, not the tag commit, so the current commit was always being used, not the actual latest commit
use git rev-list to resolve the commit for the tag

fix latest tagged commit

---

chartpress.py

Closes https://github.com/jupyterhub/chartpress/issues/61.
In short, it makes sense to me to ensure that whatever is specified in the Helm chart's requirements.yaml is up to date with what is packaged.

Ensure to honor requirements.yaml before publishing a chart

---

.bumpversion.cfg
.travis.yml
RELEASE.md
dev-requirements.txt

Removes manual edit & commit & tag steps from the release process.
cf https://github.com/jupyterhub/team-compass/issues/213#issuecomment-537712330
/cc @manics

Adopt bump2version for automating version bumps

---

CHANGELOG.md
RELEASE.md

I'm not 100% on this, should I bump this to 0.5.0 because there are new features and minor tweaks of behavior, or make it 0.4.4 as it mainly fixes bugs and weird behavior?
This is what makes me thing it should be 0.5.0:
- Add --force-build / --force-push, and don't let --tag imply it [#70](https://github.com/jupyterhub/chartpress/pull/70) ([@consideRatio](https://github.com/consideRatio))
- `helm dependency update` is now run as part of publishing, this ensures we honor requirements.yaml before publishing a chart [#69](https://github.com/jupyterhub/chartpress/pull/69) ([@consideRatio](https://github.com/consideRatio))

Update changelog for 0.5.0

---

README.md
chartpress.py
tests/test_helpers.py
tests/test_repo_interactions.py

Fixes #86 with 14f44dc + test updates.
In short, we now make `0.9.0-alpha.1.095.123asdf` become `0.9.0-alpha.1.n095.h123asdf` to ensure we never have a numerical identifier with a leading zero, which is breaking Helm 3 usage of our chart because its dependency masterminds/semver now does a better job verifying if the version is a valid semver version etc.
I failed to spot the suggested version with a leading zero in a fully numerical identifier wasn't a valid semver version before =/
This will need a minor version bump for a release, and could once again cause issues from chartpress that @henchc @betatim has helped worked through in the past for binderhub and mybinder.org.

Prefix build info with n and h to ensure SemVer 2 validity to solve Helm 3 compatibility

---

README.md
chartpress.py
tests/conftest.py
tests/test_helm_chart/chartpress_alternative.yaml
tests/test_repo_interactions.py

Allows building individual images without the prefix+name structure
in nbviewer, I want to build `jupyter/nbviewer` and `jupyter/nbviewer-statuspage`, but use `jupyter/nbviewer-` as prefix.
I know I *can* use `jupyter/` as prefix and hve image names `nbviewer`, `nbviewer-statuspage`, but this seems like something that might come up again.

support overriding imageName

---

.flake8
.travis.yml
README.md
dev-requirements.txt
tests/README.md

This is following discussion in https://github.com/jupyterhub/team-compass/issues/317.
I also needed to solve a test error relating to flake8. In doing so I updated to use pytest-flake8 instead of pytest-flakes which seemed outdated and didn't allow me to configure flake8 in a flake8 native way which I liked a lot more than introducing some custom way to configure things.

CI: publish tags without tests and test python 3.6-3.8

---

chartpress.py
tests/test_chartpress.py
tests/test_repo_interactions.py

outputs list of images to stdout. Listing images implies skip-build.
for convenient consumption of the list of images, e.g. to pass to trivy for security scans
To make chartpress output pipeable, send all log messages to stderr instead of stdout, as is standard practice.
I think this closes #94 unless I misunderstood the goal there.
Since this does move prevous output to stderr, if anyone was relying on chartpress stdout, this could be considered a backward-incompatible change. But since our output was not really machine-readable, I'd call this a minor revision.

add chartpress --list-images

---

README.md
chartpress.py

I'm working to make BinderHub's CI system easy to understand and performant, current tests take at least 13 minutes to complete, but this can change by not rebuilding the binderhub Docker image on any change as we currently do.
This PR adds the feature to allow the configuration option for indvidual images, which I named to `rebuildOnContextPathChanges`. Chartpress will assume this to be True by default, but if it is set to false, it will stop including the image's docker build contextPath as something that should be monitored for a rebuild indication whenever something changes.
With this disabled, one need to manually add paths that should be monitored to trigger changes though. In the jupyterhub/binderhub repo, I tested the following chartpress.yaml configuration which worked well. …

Image config option added: rebuildOnContextPathChanges

---

CHANGELOG.md

I want to make a release in order to be able to use the rebuildOnContextPathChanges feature that benefit jupyterhub/binderhub's repo CI performance greatly, that is in PR #98.
That PR should be merged before this, but if it is merged without changes to the title, this can be merged directly as well.

Changelog for 0.7.0

---

.travis.yml

We want to avoid running tests before deploying code in general. This PR make is to by fixing a syntax error. I had nested before_script and script under the deploy section in .travis.yml which was wrong.

CI: fix syntax typo making us run tests before publish

---

README.md
chartpress.py
tests/test_helpers.py
tests/test_repo_interactions.py

This feature help us avoid publishing the same chart version twice unless `--force-publish-chart` is passed. This mirrors the `--push` and `--force-push` behavior of docker images.
There are several reasons to not push an already existing chart:
1. It can trigger other pointless actions, such as henchbot suggesting mybinder.org-deploy to update.
2. It will clutter the gh-pages branch of the helm-chart git repository we push to. This clutter is both visual for any user browsing the versions and makes the helm chart repo grow bigger and bigger.
Closes #60 (the need for this kind of feature)
Closes #73 (implementation planning)
Closes #75 (an old PR to do this pretty much)
This is the relevant implementation changing the default behavior to check unless --force-publish-chart has been passed. …

Add --force-publish-chart and default to not overwriting

---

README.md
chartpress.py
tests/test_helpers.py
tests/test_repo_interactions.py

This PR stems from needing to make a change that was complicated to make without some refactoring, but I decided to a more proper refactoring of the chartpress.py file while I was at it.
- __Reduce risk of future errors__
By making the code more readable and with less complicated parts, we make it less prone to future errors.
- __Communicate change management intent with prefix \___
By adding a prefix `_` to certain functions, I think we communicate that these functions should not be assumed to retain their function signature etc between version updates.
- __Improve code comprehension__
With improved code comprehension others can have an easier time contributing with future maintenance etc.
- __Updated function/variable names__
Function names and variable names have been updated to be …

Major refactor for readability pre 1.0.0 release

---

README.md
chartpress.py
tests/test_helm_chart/chartpress_alternative.yaml
tests/test_repo_interactions.py

Note that this PR contain the commits of #105 as well, which should be merged first I think.
Closes #88 by stripping Chart.yaml version and notifying user about doing that, and also failing loudly if Chart.yaml still is invalid SemVer2 after that small fix attempt.
Closes #89 by updating the readme.

Strip v prefixes for Chart.yaml versions for Helm3 compliancy"

---

chartpress.py

This bug was introduced in refactoring for the 1.0.0 release and wasn't
around in 0.7.0.

bugfix: multiple images built was evaluating to a single tag

---

chartpress.py

I was trying to use `chartpress` to build binderhub with some (committed) changes to the builder, which I expected to trigger the building of a new `binderhub` image, but it did not. 
So I debugged `chartpress` and noticed that the `build_images` method would assign a value to `tag` using the first image in `images`. As this was the `cleaner` image, my builder changes were not included and as a result an older commit was assigned to `tag`. That same tag was then also used for the `binderhub` image and no new image built (as it already existed). 
In `jypterhub/binderhub` with a (committed) change to `builder.py`:
Before this PR:
```
$ chartpress
Updating binderhub/Chart.yaml: version: 0.2.0-n433.h38cd307
Skipping build for jupyterhub/k8s-image-cleaner:0.2.0-n415.hac2a96f, it already exists …
```

fix: compute tag per image

---

README.md
chartpress.py

`--no-$feature` is a standard format for disabling something on a CLI, so allow this form in addition to the existing `--skip-build`.
I've typed `chartpress --no-build` *so many times* at this point, I thought I might as well make it work :)

allow standard `--no-build` prefix for disabling builds

---

chartpress.py
setup.py

This PR in practice reverts #16 which was introduced due to a bug fixed in ruamel.yaml 0.15.44. For more details see #113, but the gist of it is that there is a difference between ruamel.yaml version 0.15.43 and 0.15.44 that makes us no longer need a previously added workaround to manage the 0.15.43 behavior.
```
pip install "ruamel.yaml==0.15.43" && \
python -c "import sys; import ruamel.yaml; ruamel.yaml.YAML(typ='rt').dump({'x': '008'}, sys.stdout)"
pip install "ruamel.yaml==0.15.44" && \
python -c "import sys; import ruamel.yaml; ruamel.yaml.YAML(typ='rt').dump({'x': '008'}, sys.stdout)"
```
Closes #113
@manics and I are working to setup pre-commit to autoformat yaml files, and chartpress coercing the image tags to single quotes for no good reason is disruptive for us. See …

fix: preserve quote formatting for image tags also

---

chartpress.py

While working to debug #113 I felt that this section was a bit complicated to read as key was a very overloaded word, so in this small refactoring PR I updated variables named key / value to path_key / path_value.

refactor: rename two local variables for readability

---

.github/workflows/test.yaml
.pre-commit-config.yaml
CHANGELOG.md
README.md
RELEASE.md
chartpress.py
setup.py
tests/README.md
tests/conftest.py
tests/test_chartpress.py
tests/test_helm_chart_repo/index.yaml
tests/test_helpers.py
tests/test_repo_interactions.py

Configuration is a direct copy of https://github.com/jupyterhub/kubespawner/blob/98bb5773f0d1c8e0c065c7259511ea38103eabe9/.pre-commit-config.yaml
Is it worth it the overhead of pre-commit for just one source file? I don't know, but it's about the same amount of work to open an issue to discuss it as it is to open this PR even if we don't merge it :smile:

Add pre-commit

---

tests/conftest.py
tests/test_commands.py

Adds some unit tests that mock the `chartpress._check_call` method, which means we can test more combinations of input arguments without complicated setups.
Ideally these tests should test all variations of all input arguments, but we can add them in future whenever the method is modified (unless someone else wants to push to this PR).

Add mock tests for public chartpress methods that call commands

---

tests/conftest.py

Fixes an error in https://github.com/jupyterhub/chartpress/pull/120
Monkeypatching `chartpress.lru_cache` doesn't work because it's too late, the functions have already been decorated. Instead call cache_clear() on each decorated function.
Without this you will get a test failure if the timestamp changes causing the git hash of the new test repo to be different from the previous test- the `@lru_cache` decorated function will return the old non-existent git sha.

Fix pytest lru_cache invalidation

---

README.md
chartpress.py
tests/test_chartpress.py
tests/test_commands.py
tests/test_helm_chart/amd64only/Dockerfile
tests/test_helm_chart/chartpress.yaml
tests/test_helpers.py

In Z2JH the [singleuser image can only be built for `linux/amd64`](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/08faa6f197e478ca28ce23d083287d37096cbb36/images/singleuser-sample/Dockerfile#L1) as it depends on https://github.com/jupyter/docker-stacks/. This means we need a way to omit selected images when building a multi-image multi-architecture chart.

Add skipPlatforms option for multi-platform docker buildx images

---

.pre-commit-hooks.yaml
setup.py

Copies over pre-commit hook from [zero-to-jupyterhub](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/c68e9a4db6ca54c464cfd67ec7a5a0c63d47f874/.pre-commit-config.yaml#L42-L50) so it can be re-used.

Define pre-commit hook

---

chartpress.py

Running chartpress in a repo without tags led to the following showing up in logs because we called git to check for tags and git errored, but we didn't mute those expected errors even though we handle them.
```
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
```

fix: mute handled git error messages

---

chartpress.py
tests/test_helpers.py

Closes #131 - this has bugged me a long time! I got confused by the fact that personal access tokens behaved differently from the `${{ github.token }}` one can get from a github workflow.
I've tested this well manually now, actually by setting up a dummy repo and running it via SSH etc.

fix: use of github workflow tokens - different from PATs

---

chartpress.py
tests/test_helpers.py

`_strip_build_suffix_from_identifier` isn't used, and it has a `_` prefix indicating it's internal.

remove unused _strip_build_suffix_from_identifier

---

setup.py

https://github.com/docker/docker-py/pull/2844 was fixed in 5.0.1

Remove six (no longer needed by docker)

---

tests/conftest.py
tests/test_repo_interactions.py

everything seems to work without fixing, but good to test anyway
related to #143, looks like we handle `2.0.0-dev` tags just fine.

Add tests with dev tags and backport branches

---

.github/dependabot.yml
.github/workflows/publish.yaml
.github/workflows/test.yaml
setup.py
tests/test_repo_interactions.py

I saw that our pre-commit check failed in a PR (#142) without automatically adding a commit to fix it. I wanted to make use of the pre-commit.ci service to help out with that, so I enabled it for the repo, and I removed the pre-commit check we manually run in a github workflow.
Along with doing that, I updated some misc workflow details and removed support for Python 3.6 that has reached end of life.
There was also a test failure related to having hardcoded a logs output comparison that changed between git versions.

Drop support for py36 and misc ci maintenance

---

chartpress.py
tests/test_repo_interactions.py

allows `chartpress --reset --tag 2.0.0-dev`. Related to #150

accept --tag arg in --reset

---

README.md
chartpress.py
tests/test_commands.py
tests/test_helm_chart/chartpress.yaml
tests/test_helpers.py

This is a first pass at implementing #141 (Ability to include extra options to `docker build`). It allows users to specify extra build options in *chartpress.yaml* on a per-image basis. This is useful for taking advantage of other build options that chartpress does not explicitly support. 
I am not very familiar with pytest, so there are no tests included here. I can confirm that it is working using the --ssh option to clone a private GitHub repo in my local builds.

Allow extra options to be passed to docker build

---

.pre-commit-config.yaml
chartpress.py
tests/test_chartpress.py
tests/test_helpers.py
tests/test_repo_interactions.py

Aligning this repo to have various hooks most other jupyterhub repo's have.

pre-commit: add pyupgrade and isort (replaces reorder-python-imports)

---

README.md
chartpress.py
tests/test_chartpress.py
tests/test_commands.py
tests/test_helpers.py
tests/test_repo_interactions.py

Instead of `1.2.3-n003.habc` produce `1.2.3-0.dev.git.3.habc`
Our current dev versions don't sort correctly for various reasons:
- `n999` and `n1000` sort alphabetically, resulting in incorrect ordering
- prereleases are relative to the _most recent_ tag, which results in incorrect ordering after every release (`1.2.3` > `1.2.3-n003.habc`, when it should be the other way around) unless repos publish a prerelease tag immediately after every stable release
The only way to get prereleases to sort correctly is to produce them relative to the _next_ release, not the _previous_ release, which we get from `git describe`.
Plus, the version information is misleading - there's no indication of whether a dev version is preparing for a minor release or a major one - only that it's _after_ some …

Add `useChartVersion` and change appended version suffix (now like `1.2.3-0.dev.git.3.h123`)

---

README.md
chartpress.py
tests/test_repo_interactions.py

always count from the beginning, ensuring the count increases no matter what the base version or recent tag.
I believe this also resolves the 'implicit tag' issue in #177. We already had a [test](https://github.com/jupyterhub/chartpress/blob/main/tests/test_repo_interactions.py#L110) for this, but it didn't ensure the repo was clean, so useChartVersion passed (and it would have worked, too, since the useChartVersion workflow means committing changes to the Chart.yaml).
I'll open a separate PR trading useChartVersion for baseVersion in chartpress.yaml

don't reset commit count on each tag

---

README.md
chartpress.py
tests/conftest.py
tests/test_helpers.py
tests/test_repo_interactions.py

instead of useChartVersion. This greatly simplifies the implementation because we aren't storing state in an auto-updated field (i.e. `--reset` doesn't depend on baseVersion config anymore).
- baseVersion is only ever considered for development versions (tag unspecified)
- <del>building from a tag is guaranteed to be identical to building with `--tag` specified</del> couldn't quite do this because `--tag` conflicts with `--long` and I don't want to detangle that. I don't think that conflict should exist, but that's outside the scope here.
- When used, baseVersion is validated against the latest tag to ensure correct ordering of dev versions (including when calling `--reset` for CI purposes)
- consolidate a few repetitive git describe calls into functions

use baseVersion config to set the base version for development releases

---

chartpress.py
tests/test_repo_interactions.py

avoids confusion with `--reset --tag` which should be `--no-build --tag`
This could be done more robustly by switching to subcommands, but I'm not sure now is the time to make that change.
closes #176

Enforce that `--reset` is an exclusive argument

---

README.md
chartpress.py
dev-requirements.txt
tests/conftest.py
tests/test_helm_chart/chartpress_base_version.yaml
tests/test_helm_chart/tbump.toml
tests/test_helpers.py
tests/test_repo_interactions.py

allows clearer behavior, simpler config without dictating everyone add the same 0.dev suffix by default.
No practical effect, other than `baseVersion: 1.2.3` is equivalent to `baseVersion: 1.2.3-0.dev` instead of raising an error telling you to use `1.2.3-0.dev`.
Importantly, this is required for chartpress to be used with an automatic version-bumping tool like `tbump`.

accept non-prerelease baseVersion (append -0.dev)

---

chartpress.py
tests/test_helm_chart/chartpress.yaml
tests/test_helpers.py
tests/test_repo_interactions.py

Much like `TAG` or `LAST_COMMIT`, add an expansion for `BRANCH` to expand to the current Git branch.
This is useful if you are using OCI image caching via extraBuildArgs, like so:
```
extraBuildCommandOptions:
- --cache-to
- type=registry,ref=ghcr.io/myorg/myimg-buildcache:{BRANCH}
- --cache-from
- type=registry,ref=ghcr.io/myorg/myimg-buildcache:{BRANCH}
```
PR branches won't have TAG for us, and LAST_COMMIT will create new caches for every new Git SHA, which defeats the purpose of a `docker buildx` cache save/restore.
NOTE - I cannot get the existing tests on `main` to pass locally with current Docker release, as the default `docker build` output format doesn't match what the tests expect - if I am missing something here let me know, otherwise I will try to debug any test failures via …

Add BRANCH expansion

---

.github/workflows/publish.yaml
.github/workflows/test.yaml
dev-requirements.txt
tests/test_chartpress.py
tests/test_repo_interactions.py

Closes #191 using the simple approach of letting tests check for either outputs that is now possible to show up depending on the docker builder.

maint: let tests check the output against another set of strings

---

README.md
chartpress.py
tests/test_helpers.py

Currently Chartpress defaults to using the last existing tag with a dev suffix, but with semver this means it's older than the last tag.
This new option means the base version can be automatically inferred by incrementing the specified component (major/minor/patch) of the last tag, meaning it's no longer necessary to set base-version to the next tag.
https://github.com/yuvipanda/cryptnono/pull/12
The default behaviour is unchanged, though arguably we could default to `patch`?

Autoincrement base version from tag if not specified

---

.github/workflows/test.yaml
README.md
chartpress.py
tests/conftest.py
tests/test_helm_chart/chartpress_alternative.yaml
tests/test_helm_chart/subdir/chart/Chart.yaml
tests/test_helm_chart/subdir/chart/templates/configmap.yaml
tests/test_helm_chart/subdir/chart/values.yaml
tests/test_repo_interactions.py

This makes it easier to organise charts in a git repo, for example the chart could be under `PROJECT-NAME/helm-chart` instead of `PROJECT-NAME/helm-chart/PROJECT-NAME`, whilst still keeping chartpress.yaml at the root of the repository.
This is a Helm 3 feature https://github.com/helm/helm/issues/1979 (should we drop Helm 2 instead of having a conditional test?)

`chartPath`: Chart directory can be different from the chart name

---

chartpress.py
tests/test_repo_interactions.py

This adds a config option `--config` which accepts a file path to an alternative configuration file (e.g. `chartpress.dev.yaml`).  The PR passes all existing tests and adds a few new assertions to test the new code.
The use-case I am supporting is alternative chartpress files for different deployment contexts. For example, I have a local development context for a JupyterHub that has a couple extra convenience services, and those need different build arguments for the Hub Docker image. The way that I manage this currently is to temporarily rewrite `chartpress.yaml` with the updated values before calling it, but I would instead like to just load a different configuration file.
(The ideal implementation would be something more akin to how you can layer different configs on like you can with …

Allow specifying config file with cli option (#170)

---

chartpress.py
tests/test_repo_interactions.py

The only thing holding `chartpress` back from [compatibility with Python 3.13 was the use of `pipes`](https://peps.python.org/pep-0594/) to quote a shell expression. Ironically the `chartpress.py` was using both `shlex.quote()` and `pipes.quote()` simultaneously. This PR removes the `pipes` import and changes the call to use `shlex`
(I also saw two unused dependencies that didn't get cleaned up in tests, so I removed those.)

Remove `pipes` for compatibility with Python 3.13

---

.github/workflows/test.yaml

I understand that chartpress is supposed to work with Python 3.13, but only in main branch and not the latest release. This is meant to verify this.

ci: test against python 3.12 and 3.13

---

CHANGELOG.md

@gardleopard doing dask/dask-gateway maintenance ran into an issue with chartpress in Python 3.13, and saw that it was already fixed in the main branch but not released - so I wanted to flush the merged PRs.
Thank you @gardleopard, @adamblake, and @sunu for your work in this release!!

Add changelog for 2.3.0
