jupyterhub/chartpress

.travis.yml

- pyflakes for correctness
- get help output

very basic testing on Travis

---

chartpress.py

for more informative output, e.g.
```
Updating jupyterhub/values.yaml: hub.image: {'name': 'jupyterhub/k8s-hub', 'tag': 'fad0f64'}
Updating jupyterhub/values.yaml: singleuser.networkTools.image: {'name': 'jupyterhub/k8s-network-tools', 'tag': '81c2613'}
Updating jupyterhub/values.yaml: prePuller.hook.image: {'name': 'jupyterhub/k8s-image-awaiter', 'tag': '01eac78'}
Updating jupyterhub/values.yaml: singleuser.image: {'name': 'jupyterhub/k8s-singleuser-sample', 'tag': '5d060de'}
Updating jupyterhub/values.yaml: cull.podCuller.image: {'name': 'jupyterhub/k8s-pod-culler', 'tag': 'b2ff98e'}
```
in zero-to-jupyterhub
Additionally, fill out some docstrings

show changes being made to values.yaml

---

chartpress.py

Provide an alternative authentication method for pushing to gh-pages.

Support GitHub token for pushing gh-pages

---

chartpress.py

Coerce ruamel.yaml seq to be python list

---

chartpress.py

so we get `0.8-sha` instead of just `sha`. Makes it a little easier to see which builds are for which chart version
closes #26

include chart version as prefix in image tags

---

CHANGELOG.md
setup.py

Time to have one. We can also release 0.3.

add a changelog

---

README.md

Not all of this is obvious when you first setup chartpress

Add initial setup when starting from scratch

---

chartpress.py

If you would develop from a tagged commit locally, you would be forced
to rebuild without this change, as the generated tag wouldn't be found
either locally or remotely.
Consider for example `0.9.0-alpha.1+000.asdf123`. With this PR, it becomes `0.9.0-alpha.1` if the `asdf123` commit is the same.

Don't append +build on tagged commits

---

README.md
chartpress.py

for images that appear multiple times in the chart (e.g. same image in multiple profiles in z2jh)

support valuesPath being a list of paths

---

README.md
chartpress.py
tests/README.md
tests/test_repo_interactions.py

Add --force-build / --force-push, and don't let --tag imply it

---

chartpress.py

Fixes #76 
Checks if images have been configured before appending chart paths.

Make images optional again

---

.travis.yml
RELEASE.md
dev-requirements.txt

Update for PyPI CD on git tag pushes

---

.travis.yml

Closes #91 by testing helm3 also.

CI: Test chartpress usage with both helm2 and helm3

---

chartpress.py

and clarify that the issue is only about installing charts from repositories not deploying charts themselves
related to https://github.com/jupyterhub/mybinder.org-deploy/issues/1725

only apply strict version checking for charts to be published

---

chartpress.py
tests/test_chartpress.py

Fix --list-images to not update Chart.yaml's version

---

CHANGELOG.md

Main feature: multi-architecture builds with `docker buildx`

Changelog for 1.1.0

---

.github/workflows/test.yaml
RELEASE.md
tests/conftest.py
tests/test_repo_interactions.py

Related to https://github.com/jupyterhub/team-compass/issues/412

Rename master to main

---

.github/workflows/test.yaml
dev-requirements.txt

So it's easier for folks to see coverage gaps

upload test coverage to codecov

---

CHANGELOG.md
README.md

- docs: fix headings to not be undefined links
- Add changelog for 2.0.0

Add changelog for 2.0.0

---

tests/test_chartpress.py

maint: make tests handle buildx 0.10+ and OCI index/manifest responses

---

CHANGELOG.md

We've got some unreleased features :smile:

Add changelog for 2.2.0
